apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  type: NodePort
  ports:
    - protocol: TCP
      port: 80           # Port exposed within cluster
      targetPort: 3000   # Port in your container
      nodePort: 32000    # Optional: specify or let K8s assign a port between 30000–32767

